title: My Awesome Blog Title
author: WhimsBV
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Just checking out GitHub Pages and how to create a site via 

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
